# Generated by Django 3.2.8 on 2021-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default='WELCOME TO SEVEN.', max_length=100),
        ),
    ]
